services:

  haystack-api:
#    image: "deepset/haystack:cpu"
    volumes:
      - ./rest_api/rest_api/pipeline:/opt/pipelines
    ports:
      - 8000:8000
    restart: always
    environment:
      # - DOCUMENTSTORE_PARAMS_HOST=elasticsearch
      # - PIPELINE_YAML_PATH=/opt/pipelines/lukaz.haystack-pipeline.yml
      # - PIPELINE_YAML_PATH=/home/user/rest_api/pipeline/lukaz.haystack-pipeline.yml
      - QUERY_PIPELINE_NAME=query
      - ELASTIC_HOST=lukaz.es.us-central1.gcp.cloud.es.io
      - ELASTIC_PASSWORD=xMXJXnKHrWNjmcbzDpr0nweF
      - CONCURRENT_REQUEST_PER_WORKER=1
      - TOKENIZERS_PARALLELISM=false
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.6"
    ports:
      - 9200:9200
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    healthcheck:
        test: curl --fail http://localhost:9200/_cat/health || exit 1
        interval: 10s
        timeout: 90s
        retries: 10
