# To allow your IDE to autocomplete and validate your YAML pipelines, name them as <name of your choice>.haystack-pipeline.yml

version: ignore

components:    # define all the building-blocks for Pipeline
  - name: DocumentStore
    type: ElasticsearchDocumentStore
    params:
      host: tekr.es.europe-west3.gcp.cloud.es.io
      port: 9243
      api_key: TJtRNqXYQzCP2vjhdrh7pA
      api_key_id: QEgMuIIBPWdvGDaDNqWr
      scheme: https
      ca_certs: /etc/ssl/certs/ca-certificates.crt
      verify_certs: true
      similarity: cosine
      embedding_dim: 768
  - name: Retriever
    type: EmbeddingRetriever
    params:
      document_store: DocumentStore    # params can reference other components defined in the YAML
      embedding_model: sentence-transformers/multi-qa-mpnet-base-dot-v1
      model_format: sentence_transformers
  - name: AnswerGeneratorOpenAI       # custom-name for the component; helpful for visualization & debugging
    type: OpenAIAnswerGenerator    # Haystack Class name for the component
    params:
      api_key: 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
      max_tokens: 100
      temperature: 0
      model: text-davinci-002
      frequency_penalty: 0
      presence_penalty: 0
  - name: TextFileConverter
    type: TextConverter
  - name: PDFFileConverter
    type: PDFToTextConverter
  - name: Preprocessor
    type: PreProcessor
    params:
      split_by: sentence
      split_length: 100
      split_respect_sentence_boundary: false
      clean_whitespace: false
      clean_empty_lines: false
  - name: FileTypeClassifier
    type: FileTypeClassifier

pipelines:
  - name: query
    nodes:
      - name: Retriever
        inputs: [Query]
      - name: AnswerGeneratorOpenAI
        inputs: [Retriever]
  - name: indexing
    nodes:
      - name: FileTypeClassifier
        inputs: [File]
      - name: TextFileConverter
        inputs: [FileTypeClassifier.output_1]
      - name: PDFFileConverter
        inputs: [FileTypeClassifier.output_2]
      - name: Preprocessor
        inputs: [PDFFileConverter, TextFileConverter]
      - name: Retriever
        inputs: [Preprocessor]
      - name: DocumentStore
        inputs: [Retriever]
